run(mlpipeline_unittest.Test_StudyDataSingleton)

run(mlfsl_unittest.Test_RegistrationFacade)
run(mlfsl_unittest.Test_KineticsFacade)
run(mlfsl_unittest.Test_SessionData)

run(mlfsl_unittest.Test_HO15ModelLayer)
run(mlfsl_unittest.Test_ModelLayer)
run(mlfsl_unittest.Test_KineticsModelLayer)
run(mlfsl_unittest.Test_FlirtVisitor)
run(mlfsl_unittest.Test_FlirtVisitor)

run(mlfsl_unittest.Test_MultispectralRegistrationBuilder)
run(mlpet_unittest.Test_PETRegistrationBuilder)
run(mlpet_unittest.Test_MRRegistrationBuilder)

run(mlfsl_unittest.Test_MultispectralAlignmentBuilder)
run(mlarbelaez_unittest.Test_GluTAlignmentDirector)
run(mlarbelaez_unittest.Test_GluTAlignmentBuilder)

run(mlmr_unittest.Test_MRAlignmentDirector)
run(mlpet_unittest.Test_PETAlignmentDirector)
run(mlpet_unittest.Test_PLaifAlignmentDirector)
run(mlpet_unittest.Test_PETImagingBuilder)
run(mlpet_unittest.Test_FlirtBuilder)
run(mlpet_unittest.Test_FslBuilder)

run(mlfsl_unittest.Test_FslVisitor)
run(mlfsl_unittest.Test_FlirtVisitor)